### ISSUE TITLE
Python Fatal error

### ISSUE THREAD

**Issue by pablodig** [bpteague/cytoflow#258] opened 2020-03-22 14:23 UTC
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
OSX 10.15.3

### SEVERITY (Critical? Major? Minor? Enhancement?):
Critical
### DESCRIPTION:
  - What were you trying to do? Open CytoFlow app
  - What happened? It didn't open due to a critical error
  - What did you expect to happen? To open
  
**Don't forget to attach the log file to this bug report!** 
Fatal Python error: Aborted

Current thread 0x0000000111120dc0 (most recent call first):
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/ui/qt4/init.py", line 37 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2452 in resolve
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446 in load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 217 in import_toolkit
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 263 in find_toolkit
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/toolkit.py", line 27 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 25 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "", line 219 in _call_with_frames_removed
File "", line 1023 in _handle_fromlist
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/qt4/__init__.py", line 25 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2452 in resolve
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446 in load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 272 in find_toolkit
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/toolkit.py", line 109 in toolkit
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/toolkit_traits.py", line 8 in ColorTrait
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traits/traits.py", line 1236 in Color
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traits/traits.py", line 522 in __call__
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/code_editor.py", line 49 in ToolkitEditorFactory
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/code_editor.py", line 37 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/api.py", line 24 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/__init__.py", line 23 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "", line 219 in _call_with_frames_removed
File "", line 941 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/api.py", line 36 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/workflow.py", line 54 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 280 in remote_main
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 93 in run
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 258 in _bootstrap
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/popen_fork.py", line 73 in _launch
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/popen_fork.py", line 19 in __init__
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/context.py", line 277 in _Popen
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/context.py", line 223 in _Popen
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 105 in start
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 261 in start_remote_process
File "/Users/pablo/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 110 in run_gui
File "/Users/pablo/opt/anaconda3/envs/cytoflow/bin/cytoflow", line 11 in

**Comment by bpteague** [comment] 2020-07-04 03:05
Pretty sure this is a duplicate of #252

**Closed by bpteague** 2020-07-04 03:05 UTC
