### ISSUE TITLE
Cryptic message on beads calibration "invalid value encountered in double_scalars"

### ISSUE THREAD

**Issue by NicholasDeLateur** [bpteague/cytoflow#197] opened 2018-05-17 17:17 UTC
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
When calibrating beads I recieved the message in yellow "invalid value encountered in double_scalars". I'm not sure what it means. It allowed me to perform my workflow as normal however. I have attached the beads file, but not sure if it's about the beads file itself or the crypticness of the message. 
[180515 Inductions_001_Specimen_005_C1_C01_005.zip](https://github.com/bpteague/cytoflow/files/2014155/180515.Inductions_001_Specimen_005_C1_C01_005.zip)

  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment] 2018-07-14 12:33
I'm unable to reproduce this.  Which channel(s) were you calibrating, and what units?  Can you reproduce it?

**Comment by bpteague** [comment] 2018-07-14 12:33
also, thanks for the bug report -- it helped me discover and squash an unrelated bug which broke this module pretty epically.

**Comment by bpteague** [comment] 2018-07-14 12:45
ah, now i've got a repro

**Comment by bpteague** [comment] 2018-07-14 12:46
also, omg the pac blue channel is just ugly.  i hope you're not measuring blue with this experiment.

**Comment by bpteague** [comment] 2018-07-14 12:57
it's a divide-by-zero warning in the peak-finding code.  i don't understand the underlying algorithm well enough to figure out why it's unhappy -- but it doesn't seem to affect the functioning of the algorithm?  Closing for now -- reopen if you can correlate it with some actual problem in the operation of the program.

**Closed by bpteague** 2018-07-14 12:57 UTC
