### ISSUE TITLE
Cannot run on Windows 8.1: "'ascii' codec can't decode byte 0xdd in position 8: ordinal not in range(128)"

### ISSUE THREAD

**Issue by blakeelias** [bpteague/cytoflow#77] opened 2017-03-22 17:43 UTC
From BioCEL student Gizem Gumuskaya <gmsky@mit.edu>:

> I'm operating on windows 8.1 64bit and I downloaded cytoflow-64.exe from this link: 
> https://bintray.com/bpteague/cytoflow/cytoflow#files
> as well as cytoflow-64.exe from this link: http://bpteague.github.io/cytoflow/ (v0.4.1 for Windows (64 bit)) and it's a windows 8.1 64bit and both of them give me the same the same error below:
> 
> ![1](https://cloud.githubusercontent.com/assets/393923/24212285/3d43802a-0f05-11e7-84cb-6e9aeff4e355.JPG)
>

**Comment by bpteague** [comment] 2017-04-29 15:54
Duplicate of #83

**Closed by bpteague** 2017-04-29 15:54 UTC
