### ISSUE TITLE
Issue launching Cytoflow in Mac OS Catalina (10.15.3)

### ISSUE THREAD

**Issue by yoganeuron** [bpteague/cytoflow#252] opened 2020-03-06 15:47 UTC
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do?
Install and launch Cytoflow 1.0 for the first time
  - What happened?
After downloading .zip file from the website, MAC prompts with saying that it cannot verify the developer -- I override this and attempt to open the program anyway. It never opens.
I installed again via Anaconda, the module will not launch.

  - What did you expect to happen?
Cytoflow would open
  
**Don't forget to attach the log file to this bug report!** 
The error thrown by Anaconda is as follows:

Fatal Python error: Aborted

Current thread 0x0000000115662dc0 (most recent call first):
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/ui/qt4/init.py", line 37 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2451 in resolve
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2445 in load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 217 in import_toolkit
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 263 in find_toolkit
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/toolkit.py", line 27 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 25 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "", line 219 in _call_with_frames_removed
File "", line 1023 in _handle_fromlist
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/qt4/__init__.py", line 25 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2451 in resolve
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2445 in load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/pyface/base_toolkit.py", line 272 in find_toolkit
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/toolkit.py", line 109 in toolkit
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/toolkit_traits.py", line 8 in ColorTrait
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traits/traits.py", line 1236 in Color
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traits/traits.py", line 522 in __call__
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/code_editor.py", line 49 in ToolkitEditorFactory
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/code_editor.py", line 37 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/api.py", line 24 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/editors/__init__.py", line 23 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "", line 219 in _call_with_frames_removed
File "", line 941 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/traitsui/api.py", line 36 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/workflow.py", line 54 in 
File "", line 219 in _call_with_frames_removed
File "", line 678 in exec_module
File "", line 665 in _load_unlocked
File "", line 955 in _find_and_load_unlocked
File "", line 971 in _find_and_load
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 280 in remote_main
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 93 in run
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 258 in _bootstrap
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/popen_fork.py", line 73 in _launch
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/popen_fork.py", line 19 in __init__
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/context.py", line 277 in _Popen
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/context.py", line 223 in _Popen
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/multiprocessing/process.py", line 105 in start
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 261 in start_remote_process
File "/Users/sarah/opt/anaconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflowgui/run.py", line 110 in run_gui
File "/Users/sarah/opt/anaconda3/envs/cytoflow/bin/cytoflow", line 11 in

**Comment by Artemis-R** [comment] 2020-05-27 23:28
Same problem, running Catalina Version 10.15.3 (19D76).

**Comment by bpteague** [comment] 2020-07-04 02:12
Hi @yoganeuron @Artemis-R  - thanks for the bug report. Mac support pretty much always lags behind because I am on a Mac very (very!) infrequently.  That said, I have managed to reproduce this, so hopefully I'll get a fix out in the next point release. Stay tuned.

**Comment by bpteague** [comment] 2020-07-04 03:16
This is almost certainly related to https://bugs.python.org/issue33725 -- unfortunately, `cytoflow` is already using `spawn` instead of `fork` for multiprocessing. The backtrace seems to indicate that it's a `qt` or a `pyqt` issue.

**Comment by bpteague** [comment] 2020-07-04 03:43
Fixed with commit 0e12c913b4492dcd9933e5ec889146f02a93b693. The next point release should work with Catalina (:

**Closed by bpteague** 2020-07-04 03:43 UTC

**Comment by yoganeuron** [comment] 2020-07-05 21:53
Thank you!!
ᐧ
